// app/layout.js
import './globals.css'
import MainLayout from './MainLayout'

export const metadata = {
  title: 'Pet Match',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
